version: "3.3"

services:

  traefik:
    image: traefik:2.0
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.front_router.rule=Host(`$BASE_DOMAIN`)
      - traefik.http.services.front_service.loadbalancer.server.port=8080
    volumes:
       - ./frontend:/usr/src/app/source
       - /usr/src/app/source/node_modules
    environment:
       VUE_APP_API_URI: ${API_URL}
       VUE_APP_FRONT_URL: ${FRONT_URL}
       VUE_APP_GOOGLE_PLACES_API_KEY: ${GOOGLE_PLACES_API_KEY}
       VUE_APP_ALGOLIA_ID: ${ALGOLIA_ID}
       VUE_APP_ALGOLIA_SECRET_KEY: ${ALGOLIA_SECRET_KEY}

  api:
    image: nginx:stable-alpine
    labels:
      - traefik.enable=true
      - traefik.http.routers.api_router.rule=Host(`api.$BASE_DOMAIN`)
    volumes:
      - ./api:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    environment:
      # SESSION_DOMAIN: .${BASE_DOMAIN}
      # SANCTUM_STATEFUL_DOMAINS: ${BASE_DOMAIN}
      GOOGLE_PLACES_API_KEY: ${GOOGLE_PLACES_API_KEY}
      ALGOLIA_APP_ID: ${ALGOLIA_ID}
      ALGOLIA_SECRET: ${ALGOLIA_SECRET_KEY}

  mysql:
    image: mysql:5.7.29
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build:
      context: ./docker/api/.
    volumes:
      - ./api:/var/www/html:delegated
    ports:
      - 9000:9000

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin_router.rule=Host(`phpmyadmin.$BASE_DOMAIN`)
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    depends_on:
      - mysql
    ports:
    - "8081:80"
    volumes:
      - /sessions
    links:
      - mysql

  composer:
    image: composer:latest
    volumes:
      - ./api:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    entrypoint: ["composer", "--ignore-platform-reqs"]

  artisan:
    build:
      context: ./docker/api/.
    volumes:
      - ./api:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

volumes:
  mysql:
